server:
  type: default
  maxThreads: 50
  minThreads: 8
  applicationConnectors:
  - type: http
    port: 9000
#  - type: https
#    port: 9443
#    keyStorePath: example.keystore
#    keyStorePassword: example
  adminConnectors:
  - type: http
    port: 9001
#  - type: https
#    port: 9444
#    keyStorePath: example.keystore
#    keyStorePassword: example

logging:
  level: INFO
  loggers:
    com.vcl3: DEBUG

jerseyClientConfiguration:
  # The socket timeout value. If a read or write to the underlying
  # TCP/IP connection hasn't succeeded after this duration, a
  # timeout exception is thrown.
#  timeout: 500ms
  timeout: 2000ms
  # The connection timeout value. If a TCP/IP connection cannot be
  # established in this time, a timeout exception is thrown.
  connectionTimeout: 500ms
  # The time a TCP/IP connection to the server is allowed to
  # persist before being explicitly closed.
  timeToLive: 1 hour
  # If true, cookies will be persisted in memory for the duration
  # of the client's lifetime. If false, cookies will be ignored
  # entirely.
  cookiesEnabled: false
  # The maximum number of connections to be held in the client's
  # connection pool.
  maxConnections: 1024
  # The maximum number of connections per "route" to be held in
  # the client's connection pool. A route is essentially a
  # combination of hostname, port, configured proxies, etc.
  maxConnectionsPerRoute: 1024
  # The default value for a persistent connection's keep-alive.
  # A value of 0 will result in connections being immediately
  # closed after a response.
  keepAlive: 0s
  # The minimum number of threads to use for asynchronous calls.
  minThreads: 1
  # The maximum number of threads to use for asynchronous calls.
  maxThreads: 128
  # If true, the client will automatically decode response entities
  # with gzip content encoding.
  gzipEnabled: true
  # If true, the client will encode request entities with gzip
  # content encoding. (Requires gzipEnabled to be true).
  gzipEnabledForRequests: true

postgresConfig:
  host: 127.0.0.1
  database: ehs
  adminPort: 15432
  sessionPort: 6432
  transactionPort: 5432
  properties:
    loginTimeout: 10
    socketTimeout: 5
  app:
    user: ehs_dev
    pass: ehs_dev
  dba:
    user: ehs_dev
    pass: ehs_dev